"""Fixed lab contracts and safety ceilings."""

from typing import Final

SCENARIO_SCHEMA_VERSION = "0.1"
PACKAGE_VERSION: Final = "0.4.0"
LEGACY_EVENT_SCHEMA_VERSION = "0.1"
SCHEMA_VERSION = "0.2"
POLICY_ID = "ASL-POLICY"
POLICY_VERSION = "policy-v1"
RISK_VERSION = "risk-v1"
SCENARIO_ID = "indirect-injection-secret-exfiltration"
VIRTUAL_SECRET_PATH = "workspace/.env"
LAB_SINK_DESTINATION = "lab://exfiltration-sink"
CANARY_ID = "canary_48f1"
CORRELATION_RULE_ID = "ASL-CORR-001"
CORRELATION_RULE_VERSION = 1

MAX_DOCUMENT_BYTES = 64 * 1024
MAX_EVENT_PAYLOAD_BYTES = 64 * 1024
MAX_TOOL_BODY_BYTES = 16 * 1024
MAX_TOOL_REQUESTS = 8
MAX_EVENTS = 128
MAX_OPERATIONAL_EVENTS = 120
MAX_REPORT_BYTES = 1024 * 1024
MAX_TIMEOUT_SECONDS = 5

RULE_SCHEMA_VERSION: Final = "1.0"
DETECTION_ENGINE_VERSION: Final = "engine-v1"
REPLAY_SCHEMA_VERSION: Final = "1.0"
MAX_RULES = 64
MAX_RULE_BYTES = 64 * 1024
MAX_RULE_STEPS = 8
MAX_RULE_PREDICATES = 16
MAX_RULE_MEMBERSHIP_VALUES = 32
MAX_REPLAY_EVENTS = 10_000
MAX_REPLAY_DATABASE_BYTES = 64 * 1024 * 1024
MAX_RULE_CANDIDATES = 10_000
MAX_RULE_MATCHES = 10_000

INVESTIGATION_SCHEMA_VERSION: Final = "1.0"
EVALUATION_SCHEMA_VERSION: Final = "1.0"
EVIDENCE_FINGERPRINT_VERSION: Final = "evidence-snapshot-v1"
RULESET_FINGERPRINT_VERSION: Final = "rule-set-v1"
SUITE_FINGERPRINT_VERSION: Final = "evaluation-suite-v1"
INCIDENT_CORRELATOR_VERSION: Final = "incident-v1"
INCIDENT_TEMPLATE_VERSION: Final = "templates-v1"
METRICS_VERSION: Final = "metrics-v1"
EVALUATION_SUITE_ID: Final = "core-lab-v1"
MAX_DERIVED_ALERTS = 1_000
MAX_INVESTIGATION_TRACES = 128
MAX_TIMELINE_ENTRIES = 10_000
MAX_EVALUATION_SUITE_BYTES = 16 * 1024
MAX_EVALUATION_CASES = 3
MAX_EVALUATION_REPETITIONS = 10
MAX_EVALUATION_CHILD_RUNS = 60
MAX_EVALUATION_ARTIFACT_BYTES = 128 * 1024 * 1024
MAX_EVALUATION_SECONDS = 300

DASHBOARD_SCHEMA_VERSION: Final = "1.0"
MAX_DASHBOARD_MANIFEST_BYTES = 64 * 1024
MAX_DASHBOARD_ENTRIES = 256
MAX_DASHBOARD_RUNS = 64
MAX_DASHBOARD_INPUT_BYTES = 256 * 1024 * 1024
MAX_DASHBOARD_EVENTS = 100_000
MAX_DASHBOARD_PROJECTION_BYTES = 64 * 1024 * 1024
MAX_DASHBOARD_RESPONSE_BYTES = 1024 * 1024
MAX_DASHBOARD_QUERY_BYTES = 2 * 1024
MAX_DASHBOARD_PAGE_SIZE = 200
MAX_DASHBOARD_STARTUP_SECONDS = 30
